# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: build and push docker image to ECR

on:
  push:
    tags:
      - 'v*'

permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        java: [ '17' ]

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven Wrapper
      run: ./mvn clean package
